
# CAMPUS SECURITY SYSTEM - DATABASE CONFIGURATION

# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/campus_security_db

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password= PASSWORD

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / HIBERNATE CONFIGURATION


# Tells Hibernate which type of database we are using
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Do not automatically change our existing database tables
spring.jpa.hibernate.ddl-auto=validate

# Show SQL queries in the IntelliJ console
spring.jpa.show-sql=true

# Format SQL queries so they are easier to read
spring.jpa.properties.hibernate.format_sql=true




# Port where our Spring Boot backend will run
server.port=8080