
# CAMPUS SECURITY SYSTEM - DATABASE CONFIGURATION

# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/campus_security_db

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password= DB_PASSWORD



# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true





# Port where our Spring Boot backend will run
server.port=8080
server.address=0.0.0.0

# Change this value before deploying the system outside your computer.
app.admin.token-secret=UFH-campus-security-admin-2026-change-me
